### ISSUE TITLE
Is the Hilbert curve sequence accurate?

### ISSUE THREAD

**Issue by DBraun** [cortesi/scurve#3]
`h = hilbert.Hilbert(3, 3)`

`for i in range(15, 17):`
`        x,y,z = h[i]`
`        print(x, y, z)`

This prints
2 0 1
3 0 2

Is that an invalid increment since both the X and Z values change in one step?

**Comment by cortesi** [comment]
Hmmm... so with this code:

```python
from scurve import hilbert

h = hilbert.Hilbert(3, 3)

for i in range(15, 17):
    x,y,z = h[i]
    print x, y, z
```
 
I get the following output:

```
2 0 1
2 0 2
```

Are you sure your copy of scurve is unmodified?

**Comment by DBraun** [comment]
Thanks for checking!

```def graycode(x):
    return x^(x>>1)```

was resulting in
```TypeError: unsupported operand type(s) for >>: 'float' and 'int'```

so I (haphazardly, it seems) changed it to

```def graycode(x):
    return int(x)^(int(x)>>1)```

Nothing else was modified. Sorry for not mentioning that earlier. What would be the proper way to avoid the TypeError? I'm just using Python 3.5.3 [MSC v.1900 64 bit (AMD64)] on win32. Thanks.

**Comment by cortesi** [comment]
Ah, that explains it. I haven't ported this project to Python3 yet - there are a couple of numeric differences in how Python3 treats things like integer division which means it would need to be looked at a bit carefully. I'd certainly pull a patch that does this,  but I might not have time myself for some time.

In the meantime, things should work as expected under Python 2.
